# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sequence.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SequenceWindow(object):
    def setupUi(self, SequenceWindow):
        SequenceWindow.setObjectName("SequenceWindow")
        SequenceWindow.resize(682, 596)
        self.centralwidget = QtWidgets.QWidget(SequenceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.active_tab = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.active_tab.setFont(font)
        self.active_tab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.active_tab.setObjectName("active_tab")
        self.verticalLayout.addWidget(self.active_tab)
        self.seqViewer = QtWidgets.QTableWidget(self.centralwidget)
        self.seqViewer.setObjectName("seqViewer")
        self.seqViewer.setColumnCount(0)
        self.seqViewer.setRowCount(0)
        self.verticalLayout.addWidget(self.seqViewer)
        SequenceWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SequenceWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 21))
        self.menubar.setObjectName("menubar")
        SequenceWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SequenceWindow)
        self.statusbar.setObjectName("statusbar")
        SequenceWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SequenceWindow)
        QtCore.QMetaObject.connectSlotsByName(SequenceWindow)

    def retranslateUi(self, SequenceWindow):
        _translate = QtCore.QCoreApplication.translate
        SequenceWindow.setWindowTitle(_translate("SequenceWindow", "Sequence"))
        self.active_tab.setText(_translate("SequenceWindow", "Unknown"))
