# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fit_sine.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fit_sine(object):
    def setupUi(self, fit_sine):
        fit_sine.setObjectName("fit_sine")
        fit_sine.resize(465, 266)
        self.comboBox_chooseFile = QtWidgets.QComboBox(fit_sine)
        self.comboBox_chooseFile.setGeometry(QtCore.QRect(10, 10, 311, 25))
        self.comboBox_chooseFile.setObjectName("comboBox_chooseFile")
        self.horizontalLayoutWidget = QtWidgets.QWidget(fit_sine)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 180, 201, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fitButton.setFont(font)
        self.fitButton.setObjectName("fitButton")
        self.horizontalLayout.addWidget(self.fitButton)
        self.DoneButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DoneButton.setFont(font)
        self.DoneButton.setObjectName("DoneButton")
        self.horizontalLayout.addWidget(self.DoneButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(fit_sine)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 447, 107))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_a = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_a.setFont(font)
        self.label_a.setObjectName("label_a")
        self.horizontalLayout_2.addWidget(self.label_a)
        self.aSpinBox_1 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.aSpinBox_1.setFont(font)
        self.aSpinBox_1.setDecimals(3)
        self.aSpinBox_1.setMaximum(999.99)
        self.aSpinBox_1.setSingleStep(0.1)
        self.aSpinBox_1.setObjectName("aSpinBox_1")
        self.horizontalLayout_2.addWidget(self.aSpinBox_1)
        self.aSpinBox_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.aSpinBox_2.setFont(font)
        self.aSpinBox_2.setDecimals(3)
        self.aSpinBox_2.setMaximum(999.99)
        self.aSpinBox_2.setObjectName("aSpinBox_2")
        self.horizontalLayout_2.addWidget(self.aSpinBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_phase = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_phase.setFont(font)
        self.label_phase.setObjectName("label_phase")
        self.horizontalLayout_3.addWidget(self.label_phase)
        self.phaseSpinBox_1 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.phaseSpinBox_1.setFont(font)
        self.phaseSpinBox_1.setMaximum(999.99)
        self.phaseSpinBox_1.setObjectName("phaseSpinBox_1")
        self.horizontalLayout_3.addWidget(self.phaseSpinBox_1)
        self.phaseSpinBox_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.phaseSpinBox_2.setFont(font)
        self.phaseSpinBox_2.setMaximum(999.99)
        self.phaseSpinBox_2.setObjectName("phaseSpinBox_2")
        self.horizontalLayout_3.addWidget(self.phaseSpinBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Tpi = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Tpi.setFont(font)
        self.label_Tpi.setObjectName("label_Tpi")
        self.horizontalLayout_4.addWidget(self.label_Tpi)
        self.TpiSpinBox_1 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.TpiSpinBox_1.setFont(font)
        self.TpiSpinBox_1.setDecimals(4)
        self.TpiSpinBox_1.setMaximum(999.99)
        self.TpiSpinBox_1.setObjectName("TpiSpinBox_1")
        self.horizontalLayout_4.addWidget(self.TpiSpinBox_1)
        self.TpiSpinBox_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.TpiSpinBox_2.setFont(font)
        self.TpiSpinBox_2.setDecimals(4)
        self.TpiSpinBox_2.setMaximum(999.99)
        self.TpiSpinBox_2.setObjectName("TpiSpinBox_2")
        self.horizontalLayout_4.addWidget(self.TpiSpinBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(fit_sine)
        QtCore.QMetaObject.connectSlotsByName(fit_sine)

    def retranslateUi(self, fit_sine):
        _translate = QtCore.QCoreApplication.translate
        fit_sine.setWindowTitle(_translate("fit_sine", "Dialog"))
        self.fitButton.setText(_translate("fit_sine", "Fit"))
        self.fitButton.setShortcut(_translate("fit_sine", "Ctrl+F"))
        self.DoneButton.setText(_translate("fit_sine", "Done"))
        self.DoneButton.setShortcut(_translate("fit_sine", "Ctrl+F"))
        self.label_a.setText(_translate("fit_sine", "a"))
        self.label_phase.setText(_translate("fit_sine", "phase"))
        self.label_Tpi.setText(_translate("fit_sine", "Tpi: Pi time, us"))


