# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fit_fock_population.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fit_fock(object):
    def setupUi(self, fit_fock):
        fit_fock.setObjectName("fit_fock")
        fit_fock.resize(500, 664)
        fit_fock.setMaximumSize(QtCore.QSize(500, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(fit_fock)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_chooseFile = QtWidgets.QComboBox(fit_fock)
        self.comboBox_chooseFile.setObjectName("comboBox_chooseFile")
        self.gridLayout.addWidget(self.comboBox_chooseFile, 0, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Tpi_2 = QtWidgets.QLabel(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Tpi_2.setFont(font)
        self.label_Tpi_2.setObjectName("label_Tpi_2")
        self.horizontalLayout_4.addWidget(self.label_Tpi_2)
        self.SpinBox_Nmax = QtWidgets.QDoubleSpinBox(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_Nmax.setFont(font)
        self.SpinBox_Nmax.setDecimals(0)
        self.SpinBox_Nmax.setMaximum(30.0)
        self.SpinBox_Nmax.setProperty("value", 6.0)
        self.SpinBox_Nmax.setObjectName("SpinBox_Nmax")
        self.horizontalLayout_4.addWidget(self.SpinBox_Nmax)
        spacerItem = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_phase = QtWidgets.QLabel(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_phase.setFont(font)
        self.label_phase.setObjectName("label_phase")
        self.horizontalLayout_3.addWidget(self.label_phase)
        self.SpinBox_gamma_1 = QtWidgets.QDoubleSpinBox(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_gamma_1.setFont(font)
        self.SpinBox_gamma_1.setDecimals(3)
        self.SpinBox_gamma_1.setMaximum(999.99)
        self.SpinBox_gamma_1.setSingleStep(0.01)
        self.SpinBox_gamma_1.setProperty("value", 2.8)
        self.SpinBox_gamma_1.setObjectName("SpinBox_gamma_1")
        self.horizontalLayout_3.addWidget(self.SpinBox_gamma_1)
        self.SpinBox_gamma_2 = QtWidgets.QDoubleSpinBox(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_gamma_2.setFont(font)
        self.SpinBox_gamma_2.setReadOnly(True)
        self.SpinBox_gamma_2.setDecimals(3)
        self.SpinBox_gamma_2.setMaximum(999.99)
        self.SpinBox_gamma_2.setObjectName("SpinBox_gamma_2")
        self.horizontalLayout_3.addWidget(self.SpinBox_gamma_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_Tpi_4 = QtWidgets.QLabel(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Tpi_4.setFont(font)
        self.label_Tpi_4.setObjectName("label_Tpi_4")
        self.horizontalLayout_6.addWidget(self.label_Tpi_4)
        self.SpinBox_Ptarget_1 = QtWidgets.QDoubleSpinBox(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_Ptarget_1.setFont(font)
        self.SpinBox_Ptarget_1.setDecimals(3)
        self.SpinBox_Ptarget_1.setMaximum(30.0)
        self.SpinBox_Ptarget_1.setSingleStep(0.01)
        self.SpinBox_Ptarget_1.setProperty("value", 0.9)
        self.SpinBox_Ptarget_1.setObjectName("SpinBox_Ptarget_1")
        self.horizontalLayout_6.addWidget(self.SpinBox_Ptarget_1)
        self.SpinBox_Ptarget_2 = QtWidgets.QDoubleSpinBox(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_Ptarget_2.setFont(font)
        self.SpinBox_Ptarget_2.setDecimals(3)
        self.SpinBox_Ptarget_2.setMaximum(30.0)
        self.SpinBox_Ptarget_2.setObjectName("SpinBox_Ptarget_2")
        self.horizontalLayout_6.addWidget(self.SpinBox_Ptarget_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_a = QtWidgets.QLabel(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_a.setFont(font)
        self.label_a.setObjectName("label_a")
        self.horizontalLayout_2.addWidget(self.label_a)
        self.SpinBox_Omega_1 = QtWidgets.QDoubleSpinBox(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_Omega_1.setFont(font)
        self.SpinBox_Omega_1.setDecimals(3)
        self.SpinBox_Omega_1.setMaximum(999.99)
        self.SpinBox_Omega_1.setSingleStep(0.1)
        self.SpinBox_Omega_1.setProperty("value", 50.0)
        self.SpinBox_Omega_1.setObjectName("SpinBox_Omega_1")
        self.horizontalLayout_2.addWidget(self.SpinBox_Omega_1)
        self.SpinBox_Omega_2 = QtWidgets.QDoubleSpinBox(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_Omega_2.setFont(font)
        self.SpinBox_Omega_2.setReadOnly(True)
        self.SpinBox_Omega_2.setDecimals(3)
        self.SpinBox_Omega_2.setMaximum(999.99)
        self.SpinBox_Omega_2.setObjectName("SpinBox_Omega_2")
        self.horizontalLayout_2.addWidget(self.SpinBox_Omega_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_Tpi_3 = QtWidgets.QLabel(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Tpi_3.setFont(font)
        self.label_Tpi_3.setObjectName("label_Tpi_3")
        self.horizontalLayout_5.addWidget(self.label_Tpi_3)
        self.SpinBox_Ntarget = QtWidgets.QDoubleSpinBox(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_Ntarget.setFont(font)
        self.SpinBox_Ntarget.setDecimals(0)
        self.SpinBox_Ntarget.setMaximum(30.0)
        self.SpinBox_Ntarget.setProperty("value", 5.0)
        self.SpinBox_Ntarget.setObjectName("SpinBox_Ntarget")
        self.horizontalLayout_5.addWidget(self.SpinBox_Ntarget)
        spacerItem1 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fitButton = QtWidgets.QPushButton(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fitButton.setFont(font)
        self.fitButton.setObjectName("fitButton")
        self.horizontalLayout.addWidget(self.fitButton)
        self.DoneButton = QtWidgets.QPushButton(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DoneButton.setFont(font)
        self.DoneButton.setObjectName("DoneButton")
        self.horizontalLayout.addWidget(self.DoneButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.checkBox_RSB = QtWidgets.QCheckBox(fit_fock)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_RSB.setFont(font)
        self.checkBox_RSB.setChecked(True)
        self.checkBox_RSB.setObjectName("checkBox_RSB")
        self.gridLayout.addWidget(self.checkBox_RSB, 2, 1, 1, 1)
        self.textFitResult = QtWidgets.QTextBrowser(fit_fock)
        self.textFitResult.setMaximumSize(QtCore.QSize(16777215, 200))
        self.textFitResult.setObjectName("textFitResult")
        self.gridLayout.addWidget(self.textFitResult, 3, 0, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addLayout(self.verticalLayout_3, 4, 0, 1, 2)

        self.retranslateUi(fit_fock)
        QtCore.QMetaObject.connectSlotsByName(fit_fock)

    def retranslateUi(self, fit_fock):
        _translate = QtCore.QCoreApplication.translate
        fit_fock.setWindowTitle(_translate("fit_fock", "Dialog"))
        self.label_Tpi_2.setText(_translate("fit_fock", "N_max"))
        self.label_phase.setText(_translate("fit_fock", "gamma1E-4"))
        self.label_Tpi_4.setText(_translate("fit_fock", "P_target"))
        self.label_a.setText(_translate("fit_fock", "Tpi_0 (us)"))
        self.label_Tpi_3.setText(_translate("fit_fock", "N_target"))
        self.fitButton.setText(_translate("fit_fock", "Fit"))
        self.fitButton.setShortcut(_translate("fit_fock", "Ctrl+F"))
        self.DoneButton.setText(_translate("fit_fock", "Done"))
        self.DoneButton.setShortcut(_translate("fit_fock", "Ctrl+F"))
        self.checkBox_RSB.setText(_translate("fit_fock", "RSB"))


