# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fit_superposition_fock_population.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fit_fock_s(object):
    def setupUi(self, fit_fock_s):
        fit_fock_s.setObjectName("fit_fock_s")
        fit_fock_s.resize(416, 816)
        fit_fock_s.setMaximumSize(QtCore.QSize(500, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(fit_fock_s)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addLayout(self.verticalLayout_3, 6, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_chooseFile = QtWidgets.QComboBox(fit_fock_s)
        self.comboBox_chooseFile.setObjectName("comboBox_chooseFile")
        self.verticalLayout.addWidget(self.comboBox_chooseFile)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SpinBox_Omega_1 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_Omega_1.setFont(font)
        self.SpinBox_Omega_1.setDecimals(3)
        self.SpinBox_Omega_1.setMaximum(999.99)
        self.SpinBox_Omega_1.setSingleStep(0.1)
        self.SpinBox_Omega_1.setProperty("value", 50.0)
        self.SpinBox_Omega_1.setObjectName("SpinBox_Omega_1")
        self.gridLayout_3.addWidget(self.SpinBox_Omega_1, 0, 1, 1, 1)
        self.label_phase = QtWidgets.QLabel(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_phase.setFont(font)
        self.label_phase.setObjectName("label_phase")
        self.gridLayout_3.addWidget(self.label_phase, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fitButton = QtWidgets.QPushButton(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fitButton.setFont(font)
        self.fitButton.setObjectName("fitButton")
        self.horizontalLayout.addWidget(self.fitButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 13, 1, 1, 1)
        self.SpinBox_init_5 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_init_5.setMaximum(1.0)
        self.SpinBox_init_5.setObjectName("SpinBox_init_5")
        self.gridLayout_3.addWidget(self.SpinBox_init_5, 9, 0, 1, 1)
        self.SpinBox_init_6 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_init_6.setMaximum(1.0)
        self.SpinBox_init_6.setObjectName("SpinBox_init_6")
        self.gridLayout_3.addWidget(self.SpinBox_init_6, 10, 0, 1, 1)
        self.SpinBox_min_3 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_min_3.setMaximum(1.0)
        self.SpinBox_min_3.setObjectName("SpinBox_min_3")
        self.gridLayout_3.addWidget(self.SpinBox_min_3, 7, 1, 1, 1)
        self.SpinBox_max_2 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_max_2.setMaximum(1.0)
        self.SpinBox_max_2.setProperty("value", 1.0)
        self.SpinBox_max_2.setObjectName("SpinBox_max_2")
        self.gridLayout_3.addWidget(self.SpinBox_max_2, 6, 2, 1, 1)
        self.SpinBox_min_4 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_min_4.setMaximum(1.0)
        self.SpinBox_min_4.setObjectName("SpinBox_min_4")
        self.gridLayout_3.addWidget(self.SpinBox_min_4, 8, 1, 1, 1)
        self.SpinBox_gamma_1 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_gamma_1.setFont(font)
        self.SpinBox_gamma_1.setDecimals(3)
        self.SpinBox_gamma_1.setMaximum(999.99)
        self.SpinBox_gamma_1.setSingleStep(0.01)
        self.SpinBox_gamma_1.setProperty("value", 2.8)
        self.SpinBox_gamma_1.setObjectName("SpinBox_gamma_1")
        self.gridLayout_3.addWidget(self.SpinBox_gamma_1, 1, 1, 1, 1)
        self.SpinBox_Omega_2 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_Omega_2.setFont(font)
        self.SpinBox_Omega_2.setReadOnly(True)
        self.SpinBox_Omega_2.setDecimals(3)
        self.SpinBox_Omega_2.setMaximum(999.99)
        self.SpinBox_Omega_2.setObjectName("SpinBox_Omega_2")
        self.gridLayout_3.addWidget(self.SpinBox_Omega_2, 0, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_gamma = QtWidgets.QCheckBox(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.checkBox_gamma.setFont(font)
        self.checkBox_gamma.setObjectName("checkBox_gamma")
        self.horizontalLayout_3.addWidget(self.checkBox_gamma)
        self.checkBox_RSB = QtWidgets.QCheckBox(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.checkBox_RSB.setFont(font)
        self.checkBox_RSB.setChecked(True)
        self.checkBox_RSB.setObjectName("checkBox_RSB")
        self.horizontalLayout_3.addWidget(self.checkBox_RSB)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 13, 2, 1, 1)
        self.SpinBox_gamma_2 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_gamma_2.setFont(font)
        self.SpinBox_gamma_2.setReadOnly(True)
        self.SpinBox_gamma_2.setDecimals(3)
        self.SpinBox_gamma_2.setMaximum(999.99)
        self.SpinBox_gamma_2.setObjectName("SpinBox_gamma_2")
        self.gridLayout_3.addWidget(self.SpinBox_gamma_2, 1, 2, 1, 1)
        self.SpinBox_init_2 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_init_2.setMaximum(1.0)
        self.SpinBox_init_2.setObjectName("SpinBox_init_2")
        self.gridLayout_3.addWidget(self.SpinBox_init_2, 6, 0, 1, 1)
        self.SpinBox_min_1 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_min_1.setMaximum(1.0)
        self.SpinBox_min_1.setObjectName("SpinBox_min_1")
        self.gridLayout_3.addWidget(self.SpinBox_min_1, 5, 1, 1, 1)
        self.DoneButton = QtWidgets.QPushButton(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DoneButton.setFont(font)
        self.DoneButton.setObjectName("DoneButton")
        self.gridLayout_3.addWidget(self.DoneButton, 13, 0, 1, 1)
        self.SpinBox_min_2 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_min_2.setMaximum(1.0)
        self.SpinBox_min_2.setObjectName("SpinBox_min_2")
        self.gridLayout_3.addWidget(self.SpinBox_min_2, 6, 1, 1, 1)
        self.label_a = QtWidgets.QLabel(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_a.setFont(font)
        self.label_a.setObjectName("label_a")
        self.gridLayout_3.addWidget(self.label_a, 0, 0, 1, 1)
        self.SpinBox_min_6 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_min_6.setMaximum(1.0)
        self.SpinBox_min_6.setObjectName("SpinBox_min_6")
        self.gridLayout_3.addWidget(self.SpinBox_min_6, 10, 1, 1, 1)
        self.SpinBox_min_0 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_min_0.setMaximum(1.0)
        self.SpinBox_min_0.setObjectName("SpinBox_min_0")
        self.gridLayout_3.addWidget(self.SpinBox_min_0, 4, 1, 1, 1)
        self.SpinBox_init_0 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_init_0.setMaximum(1.0)
        self.SpinBox_init_0.setObjectName("SpinBox_init_0")
        self.gridLayout_3.addWidget(self.SpinBox_init_0, 4, 0, 1, 1)
        self.SpinBox_max_1 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_max_1.setMaximum(1.0)
        self.SpinBox_max_1.setProperty("value", 1.0)
        self.SpinBox_max_1.setObjectName("SpinBox_max_1")
        self.gridLayout_3.addWidget(self.SpinBox_max_1, 5, 2, 1, 1)
        self.SpinBox_max_3 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_max_3.setMaximum(1.0)
        self.SpinBox_max_3.setProperty("value", 1.0)
        self.SpinBox_max_3.setObjectName("SpinBox_max_3")
        self.gridLayout_3.addWidget(self.SpinBox_max_3, 7, 2, 1, 1)
        self.SpinBox_max_6 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_max_6.setMaximum(1.0)
        self.SpinBox_max_6.setProperty("value", 1.0)
        self.SpinBox_max_6.setObjectName("SpinBox_max_6")
        self.gridLayout_3.addWidget(self.SpinBox_max_6, 10, 2, 1, 1)
        self.SpinBox_min_5 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_min_5.setMaximum(1.0)
        self.SpinBox_min_5.setObjectName("SpinBox_min_5")
        self.gridLayout_3.addWidget(self.SpinBox_min_5, 9, 1, 1, 1)
        self.SpinBox_init_1 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_init_1.setMaximum(1.0)
        self.SpinBox_init_1.setObjectName("SpinBox_init_1")
        self.gridLayout_3.addWidget(self.SpinBox_init_1, 5, 0, 1, 1)
        self.SpinBox_max_5 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_max_5.setMaximum(1.0)
        self.SpinBox_max_5.setProperty("value", 1.0)
        self.SpinBox_max_5.setObjectName("SpinBox_max_5")
        self.gridLayout_3.addWidget(self.SpinBox_max_5, 9, 2, 1, 1)
        self.SpinBox_init_4 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_init_4.setMaximum(1.0)
        self.SpinBox_init_4.setObjectName("SpinBox_init_4")
        self.gridLayout_3.addWidget(self.SpinBox_init_4, 8, 0, 1, 1)
        self.SpinBox_max_4 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_max_4.setMaximum(1.0)
        self.SpinBox_max_4.setProperty("value", 1.0)
        self.SpinBox_max_4.setObjectName("SpinBox_max_4")
        self.gridLayout_3.addWidget(self.SpinBox_max_4, 8, 2, 1, 1)
        self.SpinBox_init_3 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_init_3.setMaximum(1.0)
        self.SpinBox_init_3.setObjectName("SpinBox_init_3")
        self.gridLayout_3.addWidget(self.SpinBox_init_3, 7, 0, 1, 1)
        self.SpinBox_max_0 = QtWidgets.QDoubleSpinBox(fit_fock_s)
        self.SpinBox_max_0.setMaximum(1.0)
        self.SpinBox_max_0.setProperty("value", 1.0)
        self.SpinBox_max_0.setObjectName("SpinBox_max_0")
        self.gridLayout_3.addWidget(self.SpinBox_max_0, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.SpinBox_Nmax = QtWidgets.QSpinBox(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_Nmax.setFont(font)
        self.SpinBox_Nmax.setMaximum(6)
        self.SpinBox_Nmax.setObjectName("SpinBox_Nmax")
        self.gridLayout_3.addWidget(self.SpinBox_Nmax, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.SpinBox_offset = QtWidgets.QDoubleSpinBox(fit_fock_s)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SpinBox_offset.setFont(font)
        self.SpinBox_offset.setDecimals(3)
        self.SpinBox_offset.setMaximum(1.0)
        self.SpinBox_offset.setSingleStep(0.1)
        self.SpinBox_offset.setObjectName("SpinBox_offset")
        self.gridLayout_3.addWidget(self.SpinBox_offset, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.textFitResult = QtWidgets.QTextBrowser(fit_fock_s)
        self.textFitResult.setMaximumSize(QtCore.QSize(16777215, 200))
        self.textFitResult.setObjectName("textFitResult")
        self.gridLayout.addWidget(self.textFitResult, 5, 0, 1, 2)

        self.retranslateUi(fit_fock_s)
        QtCore.QMetaObject.connectSlotsByName(fit_fock_s)

    def retranslateUi(self, fit_fock_s):
        _translate = QtCore.QCoreApplication.translate
        fit_fock_s.setWindowTitle(_translate("fit_fock_s", "Dialog"))
        self.label_phase.setText(_translate("fit_fock_s", "gamma1E-4"))
        self.fitButton.setText(_translate("fit_fock_s", "Fit"))
        self.fitButton.setShortcut(_translate("fit_fock_s", "Ctrl+F"))
        self.checkBox_gamma.setText(_translate("fit_fock_s", "Fixed gamma"))
        self.checkBox_RSB.setText(_translate("fit_fock_s", "RSB"))
        self.DoneButton.setText(_translate("fit_fock_s", "Done"))
        self.DoneButton.setShortcut(_translate("fit_fock_s", "Ctrl+F"))
        self.label_a.setText(_translate("fit_fock_s", "Tpi_0 (us)"))
        self.label.setText(_translate("fit_fock_s", "N_max"))
        self.label_2.setText(_translate("fit_fock_s", "offset"))

